In [25]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords
import string

In [26]:
amazon_df = pd.read_csv('/home/useradd/Documentos/Amazon_Reviews/Amazon_Reviews_Python_Project/data/processed/amazon_df_EDA.csv')

In [27]:
def message_cleaning(message):
    # Verifique se a mensagem é uma string
    if isinstance(message, str):
        # Remover pontuação
        Test_punc_removed = [char for char in message if char not in string.punctuation]
        Test_punc_removed_join = ''.join(Test_punc_removed)
        # Remover stopwords
        Test_punc_removed_join_clean = [word for word in Test_punc_removed_join.split() if word.lower() not in stopwords.words('english')]
        return ' '.join(Test_punc_removed_join_clean)
    else:
        return ''  # Ou qualquer outro valor que faça sentido no seu contexto

In [28]:
amazon_df_clean = amazon_df['verified_reviews'].apply(message_cleaning)

In [30]:
# Aplicar a limpeza e manter outras colunas
amazon_df['cleaned_reviews'] = amazon_df['verified_reviews'].apply(message_cleaning)

In [31]:
print(amazon_df.columns)

Index(['rating', 'date', 'variation', 'verified_reviews', 'feedback', 'length',
       'cleaned_reviews'],
      dtype='object')


In [33]:
vectorizer = CountVectorizer(analyzer=message_cleaning, dtype=np.uint8)
amazon_df['verified_reviews'] = amazon_df['verified_reviews'].fillna('')
amazon_countvectorizer = vectorizer.fit_transform(amazon_df['verified_reviews'])

In [35]:
print(amazon_countvectorizer.toarray())

[[ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [16  0  0 ...  0  0  0]
 ...
 [41  0  0 ...  0  0  0]
 [36  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [36]:
amazon_countvectorizer.shape

(3150, 99)

In [37]:
X = pd.DataFrame(amazon_countvectorizer.toarray())

In [38]:
X

0   1   2   3   4   5   6   7   8   9   ...  89  90  91  92  93  94  95  \
0      1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     16   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3     18   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
4      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
3145   3   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3146  12   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3147  41   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3148  36   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3149   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

      96  97  98  
0      0   0   0  
1      0   0   0  
2      0   0   0  
3      0   0   0  
4      0   0   0  
...   ..  ..  ..  
3145   0   0   0  
3146   0   0   0  
3147   0   0   0  
3148   0   0   0  
3149   0   0   0  

[3150 rows x 99 columns]

In [42]:
X.to_csv('/home/useradd/Documentos/Amazon_Reviews/Amazon_Reviews_Python_Project/data/processed/X.csv', index=False)

In [44]:
amazon_df_clean = amazon_df

In [46]:
amazon_df_clean.to_csv('/home/useradd/Documentos/Amazon_Reviews/Amazon_Reviews_Python_Project/data/processed/amazon_df_clean.csv', index=False)